Laravel8.0+MySQL+Laradockで簡易的なECサイトを作る 二章終了
hakaz84/laravel-ec-practice pull request #4
Opened 2022-07-10 10:09 UTC by hakaz84

↓やった
https://note.com/mukae9/n/naf7dff31b4db

2022-07-10 10:31 UTC, akasatati commented
@hakaz84 
developに向けてください
<img width="587" alt="スクリーンショット 2022-07-10 19 30 22" src="https://user-images.githubusercontent.com/18277711/178141139-aeb54a95-9b72-450a-9078-48a1952e2ad3.png">

2022-07-10 10:52 UTC, akasatati requested changes

2022-07-10 10:52 UTC, akasatati commented on src/database/seeders/StockTableSeeder.php
> +
細かいけど2行空いている必要性はなさそうです。
```suggestion
```

2022-07-16 07:37 UTC, akasatati approved these changes
LGTM

2022-07-16 07:38 UTC, sunsound33 approved these changes

2022-07-16 07:39 UTC, merged